### ISSUE TITLE
Doesn't work if display code is in non global scope.

### ISSUE THREAD

**Issue by pschuegr** [wmluke/angular-flash#11]
This works, but as soon as the flash code is inside the menu.html, it doesn't display anymore.  It's a scope issue but I haven't quite wrapped my head around it yet.

``` html
      <body ng-app="client">
          <div flash-alert active-class="in" class="alert fade offset2 span9">
            <span class="alert-message">{{flash.message}}</span>
          </div>
          <div class='app' ng-controller="AppCtrl">
            <div id="menu" ng-include="'views/menu.html'"></div>
            <div class="container">
              <div class="row">
                <div ng-show="showSystem()" ng-cloak class="span2">
                  <div id="system" ng-include="'views/system.html'"></div>
                </div>
                <div class="span10">
                  <div class="app" ng-view=""></div>
                </div>
              </div>
            </div>
```

**Comment by wmluke** [comment]
Scoping shouldn't matter, but timing could be an issue, ie you could be setting a flash before the view has been rendered.

In which controller are you setting the flash: the AppCtrl or the routed-to controller?  Can you provide controller examples?

**Comment by pschuegr** [comment]
I'll put the controller code in as soon as I'm home, but it's in the routed controller.   Seems unlikely to be a timing issue as it happens on a button click.

**Comment by pschuegr** [comment]
Here's the controller code, not really anything special about it:

``` javascript
angular.module('client')
.controller('DictionaryEntryListCtrl', function (
  $scope, $location, Restangular, flash
) {

[...]

  $scope.add = function() {
    if($scope.valid) {
      Restangular.all("dictionary_entries").post($scope.newEntry)
      .then(function(entry) {
        $scope.dictionaryEntries.push(entry);
      });
    }
    else {
      flash.error = "Please enter correctly";
    }
  }
```

**Comment by wmluke** [comment]
I don't see anything superficially wrong with your setup.  Could it be a styling issue: something preventing the `#menu` element or the `flash-alert` within it from displaying properly?

**Comment by wmluke** [comment]
Also, FYI, `ng-show="showSystem()"` could lead to issues. Specifically, that sets up a watch on `showSystem()`.  Someone not familiar with the usage of `showSystem()` could throw a bunch of heavy lifting in it and cause some problems.  It might be a bit more performant and defensive to setup an explicit scope `$watch` which sets a flag which `ng-show` watches.  Overall, probably not a big deal...it comes down to coding style and the size of your team.

**Comment by pschuegr** [comment]
Thanks for the tip - I haven't been able to find any styling issues but I've been distracted by some back-end stuff.  Will report back.

**Comment by wmluke** [comment]
So far I haven't been able to reproduce, so I'm going to close this issue. Please reopen if you come up with more information.

Thanks for the feedback.

**Comment by pschuegr** [comment]
Yeah, apologies.  I finally had a chance to put together a simple example and it works fine.  Must be in my code somewhere. Thanks for your responses.

**Comment by pschuegr** [comment]
Ok, I tracked it down a bit further.  Here is a git repo showing the behaviour: https://github.com/verticallabs/angular-flash-test

I don't understand it fully, but there is one flash in the outer controller scope, and one in the inner ('other' scope).  The outer one is not initially visible (this may be the actual problem), but once it is visible, the flash seems to ignore it.

If the flash html code in main.html is removed, the other one seems to work fine.

Please let me know if I've done something strange.

**Comment by pschuegr** [comment]
Looks like the culprit is this:

```
$scope.$on('$destroy', function () {
  flash.clean();
});
```

When you have multiple flashes, the destruction of any one of their scopes causes all flashes to be unsubscribed, I think...
