### ISSUE TITLE
ng-show depending on flash.type

### ISSUE THREAD

**Issue by okarahan** [wmluke/angular-flash#12]
Hi guys,

I don't know if its possible with this flash service, but I try to do the following:
1. I want a ng-switch on the attribute "flash.type" if there is something like this.
2. If flash.type is error, then a div block should be display, if its success, then another part should be displayed.
3. The main problem I have is, that I have a big block on the top of my site for the flash messages and they are not visible but it takes some space and it looks horrible.

Is there a way to get a solution for this problem ? Maybe there is also a way to do this, but I didn't find from the documentation.

Regards

**Comment by wmluke** [comment]
Hi @okarahan,

Thanks for the feedback.  Instead of an uber block with a `ngSwitch`, try several blocks.  Also, just use `.hide` and `.show` as illustrated below...both come with bootstrap 2.3.

``` html
<!-- Subscribe to success flash messages. -->
<div flash-alert="success" active-class="in alert show" class="fade hide">
    <strong class="alert-heading">Win!</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>

<!-- Subscribe to error flash messages. -->
<div flash-alert="error" active-class="in alert show" class="fade hide">
    <strong class="alert-heading">Fail!</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>
```

**Comment by okarahan** [comment]
Thank you for your feedback. I will try it.

**Comment by jackypan1989** [comment]
nice hack!!
