### ISSUE TITLE
All flashes unsubscribed on scope destroy

### ISSUE THREAD

**Issue by pschuegr** [wmluke/angular-flash#16]
Apologies, I couldn't reopen the other issue (https://github.com/wmluke/angular-flash/issues/11) for some reason:

Looks like the culprit is this:

```
 $scope.$on('$destroy', function () {
   flash.clean();
});
```

When you have multiple flashes, the destruction of any one of their scopes causes all flashes to be unsubscribed, I think...

**Comment by wmluke** [comment]
@pschuegr, thanks so much for tracking this one down!  Nice work.
