### ISSUE TITLE
Feature request: have flash.clean() remove existing flashes which have already been displayed.

### ISSUE THREAD

**Issue by pschuegr** [wmluke/angular-flash#17]
As described.  Sorry for flooding your issues list!

**Comment by wmluke** [comment]
The main issue is how/what knows when a particular message has been displayed?  Specifically, we could have several `flashAlert` directives each subscribing to different types of messages?  How does the flash service or particular `flashAlert` directives know if the others have "displayed" it?  Also, what does it mean to "display" a message?  Does "display" mean that a message has been received by a `flashAlert` directive or that the user has seen the message?

Thoughts?

**Comment by pschuegr** [comment]
Yes, very valid points.  After trying to find a way to do this, I think all that I was really looking for was a way to hide the alert divs.  

(use case: when changing pages, sometimes the flash message doesn't really make sense for the next page)

I did it easily enough by removing the 'in' class from all alert divs using angular.element, but i feel like it would have been nicer to do this through the service.

**Comment by dmitry-dedukhin** [comment]
+1, it would be great to have method like cleanMessages to clean only messages but not subscribers.

**Comment by wmluke** [comment]
Hi @pschuegr, @dmitry-dedukhin,

Try calling `flash.clean()` on the Scope `$destroy` event or `$routeChangeSuccess` event...

``` javascript
scope.$on('$destroy', function(){
    flash.clean();
});

scope.$on('$routeChangeSuccess', function(){
    flash.clean();
});
```

**Comment by dmitry-dedukhin** [comment]
Hi, @wmluke,

This is not the case, I think.
My use case is the following.
After some user action I show an error, e.g. when user selects wrong date. And I do not allow user to close that message. When user selects correct date I want to clean that error message, but I don't know how.

**Comment by rsiddle** [comment]
@wmluke I'm using the following within my MainCtrl and it doesn't seem to be clearing any of the messages. 

``` javascript

scope.$on('$routeChangeSuccess', function(){
    flash.clean();
});
```

**Comment by stevebering** [comment]
I am attempting to run flash.clean on any route change by running the following:

```
$rootScope.$on('$routeChangeSuccess', function() {
    flash.clean();
});
```

However, my alerts won't go away. Am I missing something?

**Comment by joselo** [comment]
@stevebering  did you solve that?, I was trying using $locationChangeSuccess instead of $routeChangeSuccess but it doesn't work.

**Comment by wmluke** [comment]
Hi folks,

Sorry for the extended radio silence.  I think the latest release may help.  Specifically, `flash-alert` directives will now hide themselves when they receive a falsey flash message...

``` javascript
flash.error = false;
flash.error = null;
flash.error = undefined;
flash.error = '';
flash.error = NaN;
flash.error = 0;

// Applies to any flash message
flash.success = '';
```

Let me know how it goes, and thanks again for all the great feedback.

Luke

**Comment by kynan** [comment]
I can confirm the behavior @rsiddle, @stevebering and @joselo are seeing i.e. `flash.clean()` on route change doesn't clear any of the existing messages. Have worked around it by manually setting

```
flash.info = ''
flash.success = ''
flash.error = ''
```

**Comment by raimonesteve** [comment]
PR "bugfix remove dismissed messages" https://github.com/wmluke/angular-flash/pull/36 fix flash.clean();

I'm waiting @wmluke merge https://github.com/wmluke/angular-flash/pull/36 soon. Until then, you could do:

```
flash.info = null;
flash.success = null;
flash.error = null;
```
