### ISSUE TITLE
Alert takes up space when it is hidden

### ISSUE THREAD

**Issue by ChrisRose** [wmluke/angular-flash#18]
The alert still takes up space on the page when it is hidden:

http://plnkr.co/edit/3FaOT5DwdiHywFoA2tvL

Is there a way to collapse the space?

**Comment by dancek** [comment]
I wouldn't consider this a bug in angular-flash; if it's a bug, it's in Bootstrap or your CSS. :)

Just remove margins, paddings and borders when the alert is not shown.

```
.alert {
    margin: 0;
    padding: 0;
    border: 0;
}
.alert.in {
    margin: 8px;
    padding: 8px;
}
```

Change values to your liking. In case you use .alert elsewhere, specify a wrapping class in the selectors.

**Comment by dancek** [comment]
Looking at Bootstrap, this is most likely intentional on their part.

**Comment by wmluke** [comment]
I'd say this is styling issue and not really an issue with `angular-flash`.  Fortunately, you can resolve by moving `.alert` to the `active-class` attribute...

``` html
<div flash-alert active-class="in alert" class="fade">
...
</div>
```

Thanks for the feedback!

**Comment by BrianHutchison** [comment]
Great solution, thanks!
