### ISSUE TITLE
alert-message and styling disappear abruptly while alert-header fades based on transition css

### ISSUE THREAD

**Issue by tony-kerz** [wmluke/angular-flash#20]
first of all luke, sweet component, i think flash messages are ubiquitous and you did a really nice job with the project in terms of design, function and documentation.

this kind of a nit, but i would prefer to see the entire message (bootstrap round edge border style, `alert-header`, `alert-message`) fade uniformly. right now, the styled border and `alert-message` just disappear and then only the `alert-header` fades per css transition:

```
.fade {
  opacity: 0;
  -webkit-transition: opacity 1.15s linear;
  transition: opacity 1.15s linear;
}
```

i'm admittedly a javascript beginner, but i'd be happy to take a look at a PR if you could give some hints where to start looking based on your working knowledge.

regards,
tony...

**Comment by wmluke** [comment]
Hi @tony-kerz,

Thanks for the feedback, and I'm glad you're finding `angular-blocks` useful.

Out of the box the `flashAlert` directive leverages Bootstrap's `.alert` element and `.fade` transition, but I attempted to make the `flashAlert` directive loosely coupled to the CSS and HTML.  The main contract is that `flashAlert` will add `.alert-<type>` and any classes listed in `active-class` to the alert element when a matching flash message is published.  This means you can override/extend/replace Bootstrap's styling and HTML as you see fit...as long as `.alert-<type>` classes have been defined.

In your particular case, I think this means altering the `transition-property` to include other properties in addition to opacity.

Here's an example with `transition-property` set to `all`...

styles

``` css
.tk-in {
  opacity: 1;
}

.tk-fade {
  opacity: 0;
  -webkit-transition: all 1.15s linear;
  transition: all 1.15s linear;
}
```

view

``` html
<div flash-alert="info" active-class="tk-in" class="alert tk-fade">
...
</div>
```

As another example, you can ditch Bootstrap's `.fade` transition altogether and mix-in something from the wonderful [animate.css](https://daneden.me/animate)...

``` html
<div flash-alert="info" active-class="animate swing" class="alert">
...
</div>
```

And FYI: Sometime in the near future, I plan to add support for AngularJS's new [ngAnimate](http://docs.angularjs.org/api/ngAnimate) module.

Finally, I noticed in #21 that you'd like to adjust the display duration.  Was there a particular reason that the `duration` attribute didn't work for you?

``` html
<!-- Set the display duration in milli-secs.  Default is 5000, 0 disables the fade-away. -->
<div flash-alert active-class="in" class="alert fade" duration="0">
    <!-- Manually hide the alert with `hide()` -->
    <button type="button" class="close" ng-click="hide()">&times;</button>
    <strong class="alert-heading">Boo!</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>
```

Thanks again for the feedback, and let me know how it goes,
Luke

**Comment by tony-kerz** [comment]
hi luke,

thanks for the timely response.

good thought on `transition: all`, it made me read up and gain a slightly better understanding.

in this case though, i think the issue is that `flash.message` and the `alert-<type>` classes are being removed before the fade has completed.

i wasn't messing with your `duration` attribute which effects the time that the flash is visible, that value i introduced was intended to be used by the `$timeout` call to introduce a delay before `flash.message` and the `alert-<type>` classes were removed so that the transition would complete before those props were initialized.

ideally it would wait exactly for the css3 `transition-duration` prop, but i just fudged it with an overridable 2s default cause i wasn't sure how to access that value offhand.

does any of that make sense?

regards,
tony.
