### ISSUE TITLE
Bootstrap 3 alerts don't hide when not visible.

### ISSUE THREAD

**Issue by mikedevita** [wmluke/angular-flash#25]
Im probably doing something wrong, but either way i want to make sure this is documented.. I must be missing something in the examples..

Given the following code:

``` html
<div flash-alert="error" active-class="in alert alert-dismissable" duration="0">
    <button type="button" class="close" ng-click="hide()" aria-hidden="true">&times;</button>
    <strong>Error!</strong> {{flash.message}}
</div>
<div flash-alert="success" active-class="in alert alert-dismissable" duration="0">
    <button type="button" class="close" ng-click="hide()" aria-hidden="true">&times;</button>
    <strong>Success!</strong> {{flash.message}}
</div>
```

When the alerts are not triggered (hidden) their contents still show up.

![screen shot 2014-02-05 at 12 04 01 pm](https://f.cloud.github.com/assets/2991640/2090747/729771b4-8e98-11e3-8dc7-77773c46f0cc.png)

**Comment by wmluke** [comment]
Hi @mikedevita,

I think you need to add `class="fade"` to each `flashAlert` directive...

``` html
<div flash-alert="error" active-class="in alert alert-dismissable" class="fade" duration="0">
```

Also, take a look at these [styling-considerations](https://github.com/wmluke/angular-flash#styling-considerations) for other pointers.

Good luck!
Luke

**Comment by pschuegr** [comment]
Did that work for you @mikedevita?  It's not helping me.

**Comment by mikedevita** [comment]
it doesn't work for me, i dont want it to fade as im using bootstraps close feature for it. I ditched this lib and went with another.

**Comment by Rodeoclash** [comment]
Not working here either.

**Comment by jarandaf** [comment]
Same here...
