### ISSUE TITLE
Showing flash only on next page

### ISSUE THREAD

**Issue by mren** [wmluke/angular-flash#31]
How do I handle the case if there is a flash directive on the from page and on the page the form redirects to. I don't get the correct behaviour. Perhaps you can help me understand it.

My use case is the following. In my `success` callback I do the following

``` javascript
function success() {
    flash.success = 'Success';
    $location.path('/new-path');
}
```

Then the flash on my current page is notified, but because of the redirect, the `$destroy` event is called and the flash message is cleared. Thus the flash on the target page is empty.
The other variant I tried is to have the flash directive in the `$rootScope`, in this case the `$destroy` event is never called, but the flash is also not cleared while moving between pages.

I would like to use `flash.success` and `flash.error` and display the flash on the next (target) page, but only on this page and not the following pages. How can I do that?

**Comment by mren** [comment]
Should this directive work with flashes that are displayed on a different route? The more I think about it, the more it seems, that this directive is only for flashes that should be shown on the very same page.
Is this correct or am I missing something here?

Best, Mark

**Comment by wmluke** [comment]
Hi @mren,

I feel your pain.  See my comments in https://github.com/wmluke/angular-flash/issues/28#issuecomment-42751904.

Thanks again,
Luke
