### ISSUE TITLE
Can't find the app/components symlink.

### ISSUE THREAD

**Issue by tmaeda** [wmluke/angular-flash#4]
https://github.com/wmluke/angular-flash/tree/master/app

what's the ../bower_components?
I can't find this file, so my project using angular-flash can't build.

> Running "copy:dist" (copy) task
> Warning: Unable to read "app/components/angular-flash/app/components" file (Error code: ENOENT). Used --force, continuing.

**Comment by wmluke** [comment]
So I suspect one of two things...

A) You need to run `bower install`.  See http://bower.io for details.  Also, note the project Makefile, which you can run with `make install`.

OR

B) You are running this on a version of Windows that does not support symbolic links

**Comment by wmluke** [comment]
Hi tmaeda,

Take a look see at the project [contributing guidelines](https://github.com/wmluke/angular-flash#contributing) and let me know if this issue persists.

Thanks,
Luke

**Comment by tmaeda** [comment]
Hi wmluke,

Thank you for your kind advices.
`bower install` solved it.

Thanks.
