### ISSUE TITLE
Multiple flash messages of the same type?

### ISSUE THREAD

**Issue by sahansera** [wmluke/angular-flash#48]
Hi,

Does this plugin support displaying multiple flash messages of the same type. For instance, I want to display 3 messages of the type 'info'.

Thanks and regards,
./Sahan

**Comment by wmluke** [comment]
Yes.  Just use `flash-alert` directive three times...

``` html
<div id="flash1" flash-alert="info">
...
</div>

<div id="flash2" flash-alert="info">
...
</div>

<div id="flash3" flash-alert="info">
...
</div>
```

**Comment by sahansera** [comment]
@wmluke Thanks! My context was, displaying multiple server maintenance-like messages on a dashboard. I implemented it using a ng-repeat and bound the message object that gets iterated while looping.

Thanks again! :+1:
