### ISSUE TITLE
Variable fade/hide-time. Wouldn't this be a good idea?

### ISSUE THREAD

**Issue by flexd** [wmluke/angular-flash#5]
I found myself wanting to perhaps show some messages longer than others.

Wouldn't it be nice to be able to specify how long you want the message visible? And if you want it to automatically disappear.

**Comment by wmluke** [comment]
Seems reasonable. How would you like to specify these settings? In a config block or as directive attributes?

I'm leaning towards a config block to keep thing simple but this would preclude different behavior across directive instances.

Thoughts?

**Comment by flexd** [comment]
I am not sure what would be best. I think perhaps as directive attributes?

**Comment by rfink** [comment]
+1 on this issue, +1 on directive attributes (to be flexible per-instance)

**Comment by jusx** [comment]
I would like to see this as a directive attribute as well. Is anyone working on this yet?

**Comment by wmluke** [comment]
Its on my todo list...been swamped.  Of course PR's are welcome ;)

**Comment by jusx** [comment]
Alright. I may have to code this for my current project. Was hoping someone had already did this so I don't have to 
;-)
