### ISSUE TITLE
Feature idea: scoped alerts

### ISSUE THREAD

**Issue by Narretz** [wmluke/angular-flash#8]
Currently, the flash service only knows global flashes, and directives can only discriminate according to the type of alert. It would be nice if the alerts could be restricted to scope. It's strange that I define an alert message in scope A, but it will not only show in scope A, but also in scope B! for example, you have a modal open and something fails, you want to show a flash, but you also want to globally show a flash with a more generic error. currently, the modal message would be displayed globally, and the message would be out of context.
Not sure about the best way, though. Maybe when creating the directive you pass an identifier to the service, and the service keeps track of all currently active flash-ids?
However, that would mean that the message definition must be per-id, not global as of now.

**Comment by wmluke** [comment]
Thanks for the feedback @Narretz, and sorry for not getting back to you sooner.

Anyway, I initially created angular-flash to solve the problem of communicating between scopes.  For example I had a template something like...

``` html
<!-- global alert -->
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>{{ flash.heading }}</strong> {{ flash.message }}
</div>

<!-- route templates & controllers -->
<div ng-view>
  // do some controller stuff...
</view>
```

And I wanted to show and hide the "global" alert based on controller actions within the `ngView` scope without resorting to `$scope.$parent`.  A pub-sub arrangement between a service and a directive seemed like a good fit.  

So the contract with `angular-flash` is that the flash service is a publisher of flash messages and any flash directive is a subscriber to flash messages.  I feel that this is a simple and straight forward contract and I'd prefer to not complicate it with scope based conditionals.

Also, you don't really need something like `angular-flash` for hiding/showing alerts within the same scope b/c it would be overkill.  For example, you could do something like...

View:

``` html
<div ng-controller="MainCtrl">
    <div class="alert" ng-show="flash">
      <button type="button" class="close" data-dismiss="alert" ng-click="hideAlert()">&times;</button>
      <strong>{{ flash.heading }}</strong> {{ flash.message }}
    </div>
</div>
```

Controller:

``` javascript
angular.module('App').controller('MainCtrl', ['$scope', '$timeout', function($scope, $timeout){

     $scope.hideAlert = function(){
        $scope.flash = null;
     };

     // show the error flash in 5 seconds
     $timeout(function(){
          $scope.flash = {
              heading: 'Drat!',
              message: 'Fail for you!'
          };
    }, 5000);
}]);
```

Anyway, I hope this helps.

Thanks again for the feedback,
Luke

**Comment by wmluke** [comment]
@Narretz 

I just rolled out a new feature which I think can help you.  Specifically, you can now send flash messages to discrete `flashAlert` directives...

Controller:

``` javascript
// Publish an info flash to the `alert-1` subscriber
flash.to('modal-alert').info = 'Awesome modal dude!';
```

View:

``` html
<!-- Subscribe to all flash messages sent to `modal-alert`. -->
<div id="modal-alert" flash-alert active-class="in" class="alert fade">
    <strong class="alert-heading">{{flash.type}}</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>
```

Hope this helps.

Good luck!
