### ISSUE TITLE
flashing the same message multiple times in different directives

### ISSUE THREAD

**Issue by daanporon** [wmluke/angular-flash#9]
hi, first of all thanks for this plugin ... we where using it in our project and it was working really well. But now we found a few issues with it. We have a page which shows flash messages, on this page we can open a modal which also needs to show flash messages. Now when we get a flash it is shown on our page and if we open the modal after that, our flash is shown again in the modal. This is because the clean is only called when the directive has been destroyed. I think there has to be some way of popping the error message from the flash service so that it is only shown once.

Maybe this isn't something in the scope of this project ... but just wanted to let you know.

kind regards,
Daan

**Comment by wmluke** [comment]
Hello again,

Thanks for the feedback.  

Generally speaking `angular-flash` is great for displaying flash messages within **application** wide `alert` containers...meaning sending flashes to the same application level `alert` from different controllers.  I feel `angular-flash` is a bit overkill if you're just trying to display flash messages within the same controller scope.  See issue #8 for details.

However, I just rolled out a new feature which I think can help you.  Specifically, you can now send flash messages to discrete `flashAlert` directives...

Controller:

``` javascript
// Publish an info flash to the `alert-1` subscriber
flash.to('modal-alert').info = 'Awesome modal dude!';
```

View:

``` html
<!-- Subscribe to all flash messages sent to `modal-alert`. -->
<div id="modal-alert" flash-alert active-class="in" class="alert fade">
    <strong class="alert-heading">{{flash.type}}</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>
```

Hope this helps.

Good luck!
